### PR TITLE
Handle path to newman

### PR DESCRIPTION
**Pull request by jeffpriz**
I've re-worked how you get the path to Newman so that it works.

Also I've re-organized the file structure a little bit to make it simpler to upload the task for testing.  TS files are now in "src", and the built files now end up in "dist"..

### CODE REVIEW

**Comment by carlowahlstedt** [comment]
Awesome, thanks for the suggestions here. I do think the new way to get the path will be much improved.

I don't think I understand what you're trying accomplish with the reorg for testing. Specifically the removal of the root package.json. If you [look at the build](https://dev.azure.com/carlo/VSTS_Tasks/VSTS_Tasks%20Team/_apps/hub/ms.vss-ciworkflow.build-ci-hub?_a=edit-build-definition&id=11), you'll see that it's required to successfully build the project.

**Comment by jeffpriz** [comment]
I have no access to your VSTS err.. Azure Devops account so I can't look at your build...

yeah, I probably didn't need to remove that root package json.. it just was redundant for me so I took it out.. I'll restore it if you're still interested in pulling this change..

I went through and changed it this way because as it was structured, I could not tfx build tasks upload the task and get a task that worked... the node folders end up in the wrong place.  I needed to be able to tsc the task itself so that it could be uploaded successfully.  At that point maintaining two "good" copies of the package.json seems unnecessary.. as you add more tasks to the extension I suppose having a package.json at the root can help when building the whole extension..   As far as the other re-structuring (src and dist folders) I guess that's really just a convention I've followed whenever I do any typescript.. I've just found separating the .ts from the .js is helpful and clarifying.. though that's certainly a personal preference, and probably not something i should be trying to push into your repo.. 

I guess I would like to understand how you're testing this task today before you upload it to the marketplace.. as i couldn't do it the way it was structured... so I'd love to learn how you're doing it.

**Comment by carlowahlstedt** [comment]
I've build several tasks (both open source and for the company I work for) and used this [yeoman generator](https://github.com/ALM-Rangers/generator-vsts-extension) to get started. Once I learned how tasks worked, I just followed what they laid out as the convention. 

That said...testing is one of the issues I've struggled with understanding how to best do. I obviously can accomplish work with typescript, but I'm far from polished with it and testing is a specific area I struggle with. I'd really love assistance with setting up the ability to write tests for the logic to be able to verify changes. I generally just look at something, able to confirm it compiles, and then quickly verify the changes. If I published (🤞🏼not yet happened) breaking changes I would just roll it back. Not ideal, but best solution I'd had to this point.

**Comment by carlowahlstedt** [comment]
Oh, I also thought I made that Azure DevOps project publicly accessible. I'll look further into that.

**Comment by jeffpriz** [comment]
Yeah, I've struggled with setting up unit tests against the typescript tasks, so I understand your pain there (i've resorted to simply writing some test typescript to accomplish some testing). I haven't implemented Mocha and/or Chai against my tasks yet (i have one that I am working on that I need to force myself to just do it). 
But, aside from scripting tests against the typescript and running inside VSCode, I will always load my task up to a TFS or VSTS instance and run it through its paces before I publish it to the marketplace.  You published this change for accepting the path to newman and said you didn't test it.. It didn't work properly.. so the functionality that was published was not functional.. I happen to be selfish and needed that functionality so I wanted to pitch in.  So that was why, when I was working with this task, and I couldn't get it to upload, I needed to refactor some of how things went to make it so it could be uploaded and tested. 
I haven't used that particular tool that you are using (though I know the ALM Rangers are good! so trust).   But from my perspective that setup is a little bit focused to allow for extensions with multiple tasks.. I'm not super strong in my npm-foo to be able to figure out how to get the dependencies for the specific task to end up in the folder they belong in for the tasks, that's all i was trying to accomplish. Anyway for this extension, you have a single task, so the set up the way I have it, just means you tsc in the task folder instead of the root folder.. and everything works for both publishing the task, and for uploading it for testing..   :: shrug :: don't know if any of that helps or not but that's how I've been doing my tasks (both open source and for my clients).

Any way, regardless if you want to accept my pull request or not, I would appreciate a fix to the newman path to be published to the marketplace so that I may go back to using the real task and not my test/fake uploaded one.

**Comment by carlowahlstedt** [comment]
[Build failed 😔](https://dev.azure.com/carlo/VSTS_Tasks/_build/results?buildId=310&view=logs)

**Comment by jeffpriz** [comment]
I don't think I messed with the project.lock.json at all..

looked like the tsconfig was missing.. did I also remove the root tsconfig?? 
error TS5057: Cannot find a tsconfig.json file at the specified directory: '.'.

also was thinking that when I restored the package.json, I restored you package.json... the one that I have in the task folder now has a couple more packages in it, so that root package.json probably needs  to have those changes

**Comment by carlowahlstedt** [comment]
Well, it was moved and it was being referenced in another place. I fixed that, but there were other issues. I ended up just rolling back for now. Really need to build testing around this...One of these days I'll find the time, hopefully.

**Pull request merged**
