### PR TITLE
Fix #6

### LINKED ISSUE #6: Execution error with empty path to global file
If global file value is not provided, value is set to 'd:\a\1\s '.
With current implementation arg '-globalfiles' is added with this value and then newman fail since it does not found the file
`[command]C:\Windows\system32\cmd.exe /D /S /C "C:\npm\prefix\newman.cmd run --ssl-client-cert d:\a\1\s --ssl-client-key d:\a\1\s --reporter-html-template d:\a\1\s -r "cli,junit" -n 1 **--globals d:\a\1\s** -e d:\a\1\s\PostmanTests`

Seems behavior is the same for reporter-html-template, ssl-client-key but handled differently by newman

### PR DESCRIPTION
**Pull request by sebcaps**
Handle empty file for global

### CODE REVIEW

**Comment by sebcaps** [comment]
Added fix of #8

**Comment by carlowahlstedt** [comment]
Thanks for fixing these. I was just thinking yesterday how it would be nice to have a full test suite, including integration, for when changes are made.

**Comment by sebcaps** [comment]
You're welcome.
I guess tests are good Idea (moreover for a testing framework...)
For the moment, if you agree, I'll focus on support more (not to say all) Newman options ;-)

**Comment by carlowahlstedt** [comment]
No argument there. I'm sure there are people out there that would like more options.

**Pull request merged**
